In [1]:
import pandas as pd

In [31]:
df = pd.read_csv("ocorrencia01.csv",sep=",",parse_dates = ["ocorrencia_dia"])
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0

In [3]:
df.loc[1, 'ocorrencia_cidade']

'VITÓRIA'

In [5]:
df.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0

In [6]:
df.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,81017,81017,INCIDENTE GRAVE,GOIÂNIA,GO,SBNV,2022-09-30,13:40:00,0
40,80978,80978,ACIDENTE,SANTA HELENA DE GOIÁS,GO,***,2022-09-09,15:40:00,0

In [7]:
df.loc[:, 'ocorrencia_cidade']

0                SÃO PAULO
1                  VITÓRIA
2                AMERICANA
3           BELO HORIZONTE
4                   MANAUS
               ...
6764               PELOTAS
6765    LUCAS DO RIO VERDE
6766        RIO DE JANEIRO
6767                 BELÉM
6768        RIO DE JANEIRO
Name: ocorrencia_cidade, Length: 6769, dtype: object

In [8]:
df.codigo_ocorrencia.is_unique

True

In [9]:
df.ocorrencia_uf.is_unique

False

In [11]:
df.set_index('codigo_ocorrencia', inplace = True)

In [12]:
df.head()

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
codigo_ocorrencia,,,,,,,,
81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0

In [13]:
df.loc[40324]

codigo_ocorrencia2                        40324
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                       PELOTAS
ocorrencia_uf                                RS
ocorrencia_aerodromo                       SBPK
ocorrencia_dia              2010-01-05 00:00:00
ocorrencia_hora                        19:25:00
total_recomendacoes                           0
Name: 40324, dtype: object

In [14]:
df.reset_index(drop=True, inplace = True)

In [16]:
df.head(10)

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
5,81019,ACIDENTE,PORTO ALEGRE,RS,***,2022-10-03,20:50:00,0
6,81022,INCIDENTE,LOBATO,PR,***,2022-10-03,15:38:00,0
7,81021,ACIDENTE,NOVA BANDEIRANTES,MT,***,2022-10-02,19:00:00,0
8,81009,INCIDENTE GRAVE,NAVIRAÍ,MS,**NI,2022-10-01,10:10:00,0
9,81012,INCIDENTE,LINHARES,ES,***,2022-09-30,12:20:00,0

In [17]:
df.loc[5,'ocorrencia_aerodromo'] = ''

In [19]:
df.head(10)

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
5,81019,ACIDENTE,PORTO ALEGRE,RS,,2022-10-03,20:50:00,0
6,81022,INCIDENTE,LOBATO,PR,***,2022-10-03,15:38:00,0
7,81021,ACIDENTE,NOVA BANDEIRANTES,MT,***,2022-10-02,19:00:00,0
8,81009,INCIDENTE GRAVE,NAVIRAÍ,MS,**NI,2022-10-01,10:10:00,0
9,81012,INCIDENTE,LINHARES,ES,***,2022-09-30,12:20:00,0

In [29]:
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'GRAVE'

In [30]:
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,***,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,***,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0

In [32]:
df.loc[df.ocorrencia_uf == "SP"]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
13,81003,81003,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2022-09-26,18:30:00,0
14,81001,81001,INCIDENTE,BRAGANÇA PAULISTA,SP,SBBP,2022-09-25,20:00:00,0
18,80997,80997,INCIDENTE,GUARULHOS,SP,SBGR,2022-09-21,11:30:00,0
...,...,...,...,...,...,...,...,...,...
6741,39768,39768,INCIDENTE,CAMPINAS,SP,***,2010-01-21,20:45:00,0
6743,39847,39847,INCIDENTE,SOROCABA,SP,***,2010-01-20,13:10:00,0
6751,39809,39809,INCIDENTE,SÃO PAULO,SP,***,2010-01-15,15:00:00,0
6753,39828,39828,INCIDENTE,SANTOS,SP,***,2010-01-15,17:45:00,0
6759,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8

Ocorrencia_uff
**


ocorrencia_aerodromo
***
**NI


ocorrencia hora 

NULL

In [39]:
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
5,81019,81019,ACIDENTE,PORTO ALEGRE,RS,***,2022-10-03,20:50:00,0
6,81022,81022,INCIDENTE,LOBATO,PR,***,2022-10-03,15:38:00,0
7,81021,81021,ACIDENTE,NOVA BANDEIRANTES,MT,***,2022-10-02,19:00:00,0
8,81009,81009,INCIDENTE GRAVE,NAVIRAÍ,MS,**NI,2022-10-01,10:10:00,0
9,81012,81012,INCIDENTE,LINHARES,ES,***,2022-09-30,12:20:00,0

In [42]:
df.loc[df.ocorrencia_aerodromo == '***', ['ocorrencia_aerodromo']] = pd.NA

In [43]:
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
5,81019,81019,ACIDENTE,PORTO ALEGRE,RS,<NA>,2022-10-03,20:50:00,0
6,81022,81022,INCIDENTE,LOBATO,PR,<NA>,2022-10-03,15:38:00,0
7,81021,81021,ACIDENTE,NOVA BANDEIRANTES,MT,<NA>,2022-10-02,19:00:00,0
8,81009,81009,INCIDENTE GRAVE,NAVIRAÍ,MS,**NI,2022-10-01,10:10:00,0
9,81012,81012,INCIDENTE,LINHARES,ES,<NA>,2022-09-30,12:20:00,0

In [44]:
df.replace(['**NI','NULL','**','***',"****"], pd.NA, inplace=True)

In [49]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  4
ocorrencia_aerodromo        2618
ocorrencia_dia                 0
ocorrencia_hora                2
total_recomendacoes            0
dtype: int64

In [50]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  4
ocorrencia_aerodromo        2618
ocorrencia_dia                 0
ocorrencia_hora                2
total_recomendacoes            0
dtype: int64

In [51]:
df.fillna(10, inplace=True)

In [52]:
df.isna().sum()

codigo_ocorrencia           0
codigo_ocorrencia2          0
ocorrencia_classificacao    0
ocorrencia_cidade           0
ocorrencia_uf               0
ocorrencia_aerodromo        0
ocorrencia_dia              0
ocorrencia_hora             0
total_recomendacoes         0
dtype: int64

In [53]:
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,10,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,10,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0

In [54]:
df.replace([10], pd.NA, inplace=True)

In [55]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  4
ocorrencia_aerodromo        2618
ocorrencia_dia                 0
ocorrencia_hora                2
total_recomendacoes            2
dtype: int64

In [59]:
df.fillna(value={'total_recomendacoes':10}, inplace=True)

In [60]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  4
ocorrencia_aerodromo        2618
ocorrencia_dia                 0
ocorrencia_hora                2
total_recomendacoes            0
dtype: int64

In [62]:
df['total_recomendacoes_bkp'] = df.total_recomendacoes

In [63]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,total_recomendacoes_bkp
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0,0

In [65]:
df.drop(['total_recomendacoes_bkp'],axis=1, inplace = True)

In [66]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0

In [67]:
df.dropna()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6760,40414,40414,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,3:00:00,0
6762,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0

In [68]:
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,<NA>,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0

In [69]:
df.dropna(subset=['ocorrencia_uf'])

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,<NA>,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0

In [70]:
df.drop_duplicates()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,0:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,<NA>,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0